version: '3.8'

services:
  kafka-consumer-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-consumer-app
    ports:
      - "8082:8082"
      - "8083:8083"  # Management port
    environment:
      # Spring profiles
      SPRING_PROFILES_ACTIVE: docker
      
      # Kafka configuration
      KAFKA_BOOTSTRAP_SERVERS: kafka-kraft:29092
      
      # Consumer configuration
      KAFKA_CONSUMER_GROUP_ID: crypto-consumer-group
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
      KAFKA_CONSUMER_ENABLE_AUTO_COMMIT: true
      KAFKA_CONSUMER_AUTO_COMMIT_INTERVAL_MS: 1000
      KAFKA_CONSUMER_SESSION_TIMEOUT_MS: 30000
      KAFKA_CONSUMER_MAX_POLL_RECORDS: 500
      KAFKA_CONSUMER_FETCH_MIN_BYTES: 1
      KAFKA_CONSUMER_FETCH_MAX_WAIT_MS: 500
      
      # Topic configuration
      APP_KAFKA_TOPICS_DEFAULT: messages
      APP_KAFKA_TOPICS_USER_EVENTS: user-events
      APP_KAFKA_TOPICS_TRANSACTION_EVENTS: transaction-events
      APP_KAFKA_TOPICS_NOTIFICATIONS: notifications
      APP_KAFKA_TOPICS_AUDIT_LOGS: audit-logs
      APP_KAFKA_TOPICS_BATCH_PROCESSING: batch-processing
      APP_KAFKA_TOPICS_REAL_TIME_EVENTS: realtime-events
      APP_KAFKA_TOPICS_ERROR_EVENTS: error-events
      APP_KAFKA_TOPICS_METRICS: metrics
      
      # Application configuration
      SERVER_PORT: 8082
      MANAGEMENT_SERVER_PORT: 8083
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
      
      # Logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_CRP_KAFKA: DEBUG
      LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      
      # JVM options
      JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseG1GC"
      
    volumes:
      - ./logs:/app/logs
    networks:
      - kafka-network
    restart: unless-stopped
    depends_on:
      - kafka-kraft
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  kafka-network:
    external: true